### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Saxavlax001** [Nukkit-coders/AdvancedKits#2]
2018-12-25 17:56:12 [CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerInteractEvent' to 'AdvancedKits v2.0': null on com.fleynaro.advancedkits.EventListener
2018-12-25 17:56:12 [ALERT] cn.nukkit.utils.EventException
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:542)
	at cn.nukkit.level.Level.useItemOn(Level.java:1994)
	at cn.nukkit.level.Level.useItemOn(Level.java:1961)
	at cn.nukkit.Player.handleDataPacket(Player.java:2891)
	at java.util.ArrayList.forEach(Unknown Source)
	at cn.nukkit.network.Network.processPackets(Network.java:179)
	at cn.nukkit.network.Network.processBatch(Network.java:161)
	at cn.nukkit.Player.handleDataPacket(Player.java:2042)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:1076)
	at cn.nukkit.Server.tickProcessor(Server.java:853)
	at cn.nukkit.Server.start(Server.java:830)
	at cn.nukkit.Server.<init>(Server.java:513)
	at cn.nukkit.Nukkit.main(Nukkit.java:109)
Caused by: java.lang.NullPointerException
	at com.fleynaro.advancedkits.EventListener.onSign(EventListener.java:29)
	at sun.reflect.GeneratedMethodAccessor154.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
	... 18 more

**Comment by Saxavlax001** [comment]
I think it doesnt happen very often but it happened to me one or two times I think.

**Comment by PetteriM1** [comment]
1. Update your plugin to latest version (2.1)
2. Delete old config

**Comment by Saxavlax001** [comment]
ok ill try when im free.
